# Generated by Django 5.2.7 on 2025-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="recording_file",
            field=models.FileField(blank=True, null=True, upload_to="recordings/"),
        ),
    ]
